/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACy extends PCy
{
    private TCyw _cyw_;
    private TValor _valor_;

    public ACy()
    {
        // Constructor
    }

    public ACy(
        @SuppressWarnings("hiding") TCyw _cyw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setCyw(_cyw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new ACy(
            cloneNode(this._cyw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACy(this);
    }

    public TCyw getCyw()
    {
        return this._cyw_;
    }

    public void setCyw(TCyw node)
    {
        if(this._cyw_ != null)
        {
            this._cyw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cyw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cyw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cyw_ == child)
        {
            this._cyw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cyw_ == oldChild)
        {
            setCyw((TCyw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
