/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AElipse extends PElipse
{
    private TElipseEti _elipseEti_;
    private PCx _cx_;
    private PCy _cy_;
    private PRx _rx_;
    private PRy _ry_;
    private PStyle _style_;

    public AElipse()
    {
        // Constructor
    }

    public AElipse(
        @SuppressWarnings("hiding") TElipseEti _elipseEti_,
        @SuppressWarnings("hiding") PCx _cx_,
        @SuppressWarnings("hiding") PCy _cy_,
        @SuppressWarnings("hiding") PRx _rx_,
        @SuppressWarnings("hiding") PRy _ry_,
        @SuppressWarnings("hiding") PStyle _style_)
    {
        // Constructor
        setElipseEti(_elipseEti_);

        setCx(_cx_);

        setCy(_cy_);

        setRx(_rx_);

        setRy(_ry_);

        setStyle(_style_);

    }

    @Override
    public Object clone()
    {
        return new AElipse(
            cloneNode(this._elipseEti_),
            cloneNode(this._cx_),
            cloneNode(this._cy_),
            cloneNode(this._rx_),
            cloneNode(this._ry_),
            cloneNode(this._style_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElipse(this);
    }

    public TElipseEti getElipseEti()
    {
        return this._elipseEti_;
    }

    public void setElipseEti(TElipseEti node)
    {
        if(this._elipseEti_ != null)
        {
            this._elipseEti_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elipseEti_ = node;
    }

    public PCx getCx()
    {
        return this._cx_;
    }

    public void setCx(PCx node)
    {
        if(this._cx_ != null)
        {
            this._cx_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cx_ = node;
    }

    public PCy getCy()
    {
        return this._cy_;
    }

    public void setCy(PCy node)
    {
        if(this._cy_ != null)
        {
            this._cy_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cy_ = node;
    }

    public PRx getRx()
    {
        return this._rx_;
    }

    public void setRx(PRx node)
    {
        if(this._rx_ != null)
        {
            this._rx_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rx_ = node;
    }

    public PRy getRy()
    {
        return this._ry_;
    }

    public void setRy(PRy node)
    {
        if(this._ry_ != null)
        {
            this._ry_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ry_ = node;
    }

    public PStyle getStyle()
    {
        return this._style_;
    }

    public void setStyle(PStyle node)
    {
        if(this._style_ != null)
        {
            this._style_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._style_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elipseEti_)
            + toString(this._cx_)
            + toString(this._cy_)
            + toString(this._rx_)
            + toString(this._ry_)
            + toString(this._style_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elipseEti_ == child)
        {
            this._elipseEti_ = null;
            return;
        }

        if(this._cx_ == child)
        {
            this._cx_ = null;
            return;
        }

        if(this._cy_ == child)
        {
            this._cy_ = null;
            return;
        }

        if(this._rx_ == child)
        {
            this._rx_ = null;
            return;
        }

        if(this._ry_ == child)
        {
            this._ry_ = null;
            return;
        }

        if(this._style_ == child)
        {
            this._style_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elipseEti_ == oldChild)
        {
            setElipseEti((TElipseEti) newChild);
            return;
        }

        if(this._cx_ == oldChild)
        {
            setCx((PCx) newChild);
            return;
        }

        if(this._cy_ == oldChild)
        {
            setCy((PCy) newChild);
            return;
        }

        if(this._rx_ == oldChild)
        {
            setRx((PRx) newChild);
            return;
        }

        if(this._ry_ == oldChild)
        {
            setRy((PRy) newChild);
            return;
        }

        if(this._style_ == oldChild)
        {
            setStyle((PStyle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
