/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AElipseFiguras extends PFiguras
{
    private PElipse _elipse_;

    public AElipseFiguras()
    {
        // Constructor
    }

    public AElipseFiguras(
        @SuppressWarnings("hiding") PElipse _elipse_)
    {
        // Constructor
        setElipse(_elipse_);

    }

    @Override
    public Object clone()
    {
        return new AElipseFiguras(
            cloneNode(this._elipse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElipseFiguras(this);
    }

    public PElipse getElipse()
    {
        return this._elipse_;
    }

    public void setElipse(PElipse node)
    {
        if(this._elipse_ != null)
        {
            this._elipse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elipse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elipse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elipse_ == child)
        {
            this._elipse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elipse_ == oldChild)
        {
            setElipse((PElipse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
