/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFill extends PFill
{
    private TFillw _fillw_;
    private TValor _valor_;

    public AFill()
    {
        // Constructor
    }

    public AFill(
        @SuppressWarnings("hiding") TFillw _fillw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setFillw(_fillw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AFill(
            cloneNode(this._fillw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFill(this);
    }

    public TFillw getFillw()
    {
        return this._fillw_;
    }

    public void setFillw(TFillw node)
    {
        if(this._fillw_ != null)
        {
            this._fillw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fillw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fillw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fillw_ == child)
        {
            this._fillw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fillw_ == oldChild)
        {
            setFillw((TFillw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
