/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ALinea extends PLinea
{
    private TLineaEti _lineaEti_;
    private PX1 _x1_;
    private PX2 _x2_;
    private PY1 _y1_;
    private PY2 _y2_;
    private PLinestyle _linestyle_;
    private TFinfigura _finfigura_;
    private PFiguras _figuras_;

    public ALinea()
    {
        // Constructor
    }

    public ALinea(
        @SuppressWarnings("hiding") TLineaEti _lineaEti_,
        @SuppressWarnings("hiding") PX1 _x1_,
        @SuppressWarnings("hiding") PX2 _x2_,
        @SuppressWarnings("hiding") PY1 _y1_,
        @SuppressWarnings("hiding") PY2 _y2_,
        @SuppressWarnings("hiding") PLinestyle _linestyle_,
        @SuppressWarnings("hiding") TFinfigura _finfigura_,
        @SuppressWarnings("hiding") PFiguras _figuras_)
    {
        // Constructor
        setLineaEti(_lineaEti_);

        setX1(_x1_);

        setX2(_x2_);

        setY1(_y1_);

        setY2(_y2_);

        setLinestyle(_linestyle_);

        setFinfigura(_finfigura_);

        setFiguras(_figuras_);

    }

    @Override
    public Object clone()
    {
        return new ALinea(
            cloneNode(this._lineaEti_),
            cloneNode(this._x1_),
            cloneNode(this._x2_),
            cloneNode(this._y1_),
            cloneNode(this._y2_),
            cloneNode(this._linestyle_),
            cloneNode(this._finfigura_),
            cloneNode(this._figuras_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALinea(this);
    }

    public TLineaEti getLineaEti()
    {
        return this._lineaEti_;
    }

    public void setLineaEti(TLineaEti node)
    {
        if(this._lineaEti_ != null)
        {
            this._lineaEti_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lineaEti_ = node;
    }

    public PX1 getX1()
    {
        return this._x1_;
    }

    public void setX1(PX1 node)
    {
        if(this._x1_ != null)
        {
            this._x1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x1_ = node;
    }

    public PX2 getX2()
    {
        return this._x2_;
    }

    public void setX2(PX2 node)
    {
        if(this._x2_ != null)
        {
            this._x2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x2_ = node;
    }

    public PY1 getY1()
    {
        return this._y1_;
    }

    public void setY1(PY1 node)
    {
        if(this._y1_ != null)
        {
            this._y1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._y1_ = node;
    }

    public PY2 getY2()
    {
        return this._y2_;
    }

    public void setY2(PY2 node)
    {
        if(this._y2_ != null)
        {
            this._y2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._y2_ = node;
    }

    public PLinestyle getLinestyle()
    {
        return this._linestyle_;
    }

    public void setLinestyle(PLinestyle node)
    {
        if(this._linestyle_ != null)
        {
            this._linestyle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._linestyle_ = node;
    }

    public TFinfigura getFinfigura()
    {
        return this._finfigura_;
    }

    public void setFinfigura(TFinfigura node)
    {
        if(this._finfigura_ != null)
        {
            this._finfigura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finfigura_ = node;
    }

    public PFiguras getFiguras()
    {
        return this._figuras_;
    }

    public void setFiguras(PFiguras node)
    {
        if(this._figuras_ != null)
        {
            this._figuras_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._figuras_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lineaEti_)
            + toString(this._x1_)
            + toString(this._x2_)
            + toString(this._y1_)
            + toString(this._y2_)
            + toString(this._linestyle_)
            + toString(this._finfigura_)
            + toString(this._figuras_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lineaEti_ == child)
        {
            this._lineaEti_ = null;
            return;
        }

        if(this._x1_ == child)
        {
            this._x1_ = null;
            return;
        }

        if(this._x2_ == child)
        {
            this._x2_ = null;
            return;
        }

        if(this._y1_ == child)
        {
            this._y1_ = null;
            return;
        }

        if(this._y2_ == child)
        {
            this._y2_ = null;
            return;
        }

        if(this._linestyle_ == child)
        {
            this._linestyle_ = null;
            return;
        }

        if(this._finfigura_ == child)
        {
            this._finfigura_ = null;
            return;
        }

        if(this._figuras_ == child)
        {
            this._figuras_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lineaEti_ == oldChild)
        {
            setLineaEti((TLineaEti) newChild);
            return;
        }

        if(this._x1_ == oldChild)
        {
            setX1((PX1) newChild);
            return;
        }

        if(this._x2_ == oldChild)
        {
            setX2((PX2) newChild);
            return;
        }

        if(this._y1_ == oldChild)
        {
            setY1((PY1) newChild);
            return;
        }

        if(this._y2_ == oldChild)
        {
            setY2((PY2) newChild);
            return;
        }

        if(this._linestyle_ == oldChild)
        {
            setLinestyle((PLinestyle) newChild);
            return;
        }

        if(this._finfigura_ == oldChild)
        {
            setFinfigura((TFinfigura) newChild);
            return;
        }

        if(this._figuras_ == oldChild)
        {
            setFiguras((PFiguras) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
