/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APolilineaFiguras extends PFiguras
{
    private PPolilinea _polilinea_;

    public APolilineaFiguras()
    {
        // Constructor
    }

    public APolilineaFiguras(
        @SuppressWarnings("hiding") PPolilinea _polilinea_)
    {
        // Constructor
        setPolilinea(_polilinea_);

    }

    @Override
    public Object clone()
    {
        return new APolilineaFiguras(
            cloneNode(this._polilinea_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPolilineaFiguras(this);
    }

    public PPolilinea getPolilinea()
    {
        return this._polilinea_;
    }

    public void setPolilinea(PPolilinea node)
    {
        if(this._polilinea_ != null)
        {
            this._polilinea_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._polilinea_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._polilinea_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._polilinea_ == child)
        {
            this._polilinea_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._polilinea_ == oldChild)
        {
            setPolilinea((PPolilinea) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
