/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APolilinea extends PPolilinea
{
    private TPolilineaEti _polilineaEti_;
    private TPointsw _pointsw_;
    private TComillas _a_;
    private PPoints _points_;
    private TComillas _b_;
    private PStyle _style_;

    public APolilinea()
    {
        // Constructor
    }

    public APolilinea(
        @SuppressWarnings("hiding") TPolilineaEti _polilineaEti_,
        @SuppressWarnings("hiding") TPointsw _pointsw_,
        @SuppressWarnings("hiding") TComillas _a_,
        @SuppressWarnings("hiding") PPoints _points_,
        @SuppressWarnings("hiding") TComillas _b_,
        @SuppressWarnings("hiding") PStyle _style_)
    {
        // Constructor
        setPolilineaEti(_polilineaEti_);

        setPointsw(_pointsw_);

        setA(_a_);

        setPoints(_points_);

        setB(_b_);

        setStyle(_style_);

    }

    @Override
    public Object clone()
    {
        return new APolilinea(
            cloneNode(this._polilineaEti_),
            cloneNode(this._pointsw_),
            cloneNode(this._a_),
            cloneNode(this._points_),
            cloneNode(this._b_),
            cloneNode(this._style_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPolilinea(this);
    }

    public TPolilineaEti getPolilineaEti()
    {
        return this._polilineaEti_;
    }

    public void setPolilineaEti(TPolilineaEti node)
    {
        if(this._polilineaEti_ != null)
        {
            this._polilineaEti_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._polilineaEti_ = node;
    }

    public TPointsw getPointsw()
    {
        return this._pointsw_;
    }

    public void setPointsw(TPointsw node)
    {
        if(this._pointsw_ != null)
        {
            this._pointsw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pointsw_ = node;
    }

    public TComillas getA()
    {
        return this._a_;
    }

    public void setA(TComillas node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public PPoints getPoints()
    {
        return this._points_;
    }

    public void setPoints(PPoints node)
    {
        if(this._points_ != null)
        {
            this._points_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._points_ = node;
    }

    public TComillas getB()
    {
        return this._b_;
    }

    public void setB(TComillas node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    public PStyle getStyle()
    {
        return this._style_;
    }

    public void setStyle(PStyle node)
    {
        if(this._style_ != null)
        {
            this._style_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._style_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._polilineaEti_)
            + toString(this._pointsw_)
            + toString(this._a_)
            + toString(this._points_)
            + toString(this._b_)
            + toString(this._style_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._polilineaEti_ == child)
        {
            this._polilineaEti_ = null;
            return;
        }

        if(this._pointsw_ == child)
        {
            this._pointsw_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._points_ == child)
        {
            this._points_ = null;
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        if(this._style_ == child)
        {
            this._style_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._polilineaEti_ == oldChild)
        {
            setPolilineaEti((TPolilineaEti) newChild);
            return;
        }

        if(this._pointsw_ == oldChild)
        {
            setPointsw((TPointsw) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((TComillas) newChild);
            return;
        }

        if(this._points_ == oldChild)
        {
            setPoints((PPoints) newChild);
            return;
        }

        if(this._b_ == oldChild)
        {
            setB((TComillas) newChild);
            return;
        }

        if(this._style_ == oldChild)
        {
            setStyle((PStyle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
