/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APoligonoFiguras extends PFiguras
{
    private PPoligono _poligono_;

    public APoligonoFiguras()
    {
        // Constructor
    }

    public APoligonoFiguras(
        @SuppressWarnings("hiding") PPoligono _poligono_)
    {
        // Constructor
        setPoligono(_poligono_);

    }

    @Override
    public Object clone()
    {
        return new APoligonoFiguras(
            cloneNode(this._poligono_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPoligonoFiguras(this);
    }

    public PPoligono getPoligono()
    {
        return this._poligono_;
    }

    public void setPoligono(PPoligono node)
    {
        if(this._poligono_ != null)
        {
            this._poligono_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._poligono_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._poligono_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._poligono_ == child)
        {
            this._poligono_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._poligono_ == oldChild)
        {
            setPoligono((PPoligono) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
