/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ARectanguloFiguras extends PFiguras
{
    private PRectangulo _rectangulo_;

    public ARectanguloFiguras()
    {
        // Constructor
    }

    public ARectanguloFiguras(
        @SuppressWarnings("hiding") PRectangulo _rectangulo_)
    {
        // Constructor
        setRectangulo(_rectangulo_);

    }

    @Override
    public Object clone()
    {
        return new ARectanguloFiguras(
            cloneNode(this._rectangulo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARectanguloFiguras(this);
    }

    public PRectangulo getRectangulo()
    {
        return this._rectangulo_;
    }

    public void setRectangulo(PRectangulo node)
    {
        if(this._rectangulo_ != null)
        {
            this._rectangulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rectangulo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rectangulo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rectangulo_ == child)
        {
            this._rectangulo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rectangulo_ == oldChild)
        {
            setRectangulo((PRectangulo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
