/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ARectangulo extends PRectangulo
{
    private TRectanguloEti _rectanguloEti_;
    private PX _x_;
    private PY _y_;
    private TWidth _width_;
    private THeight _height_;
    private PStyle _style_;

    public ARectangulo()
    {
        // Constructor
    }

    public ARectangulo(
        @SuppressWarnings("hiding") TRectanguloEti _rectanguloEti_,
        @SuppressWarnings("hiding") PX _x_,
        @SuppressWarnings("hiding") PY _y_,
        @SuppressWarnings("hiding") TWidth _width_,
        @SuppressWarnings("hiding") THeight _height_,
        @SuppressWarnings("hiding") PStyle _style_)
    {
        // Constructor
        setRectanguloEti(_rectanguloEti_);

        setX(_x_);

        setY(_y_);

        setWidth(_width_);

        setHeight(_height_);

        setStyle(_style_);

    }

    @Override
    public Object clone()
    {
        return new ARectangulo(
            cloneNode(this._rectanguloEti_),
            cloneNode(this._x_),
            cloneNode(this._y_),
            cloneNode(this._width_),
            cloneNode(this._height_),
            cloneNode(this._style_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARectangulo(this);
    }

    public TRectanguloEti getRectanguloEti()
    {
        return this._rectanguloEti_;
    }

    public void setRectanguloEti(TRectanguloEti node)
    {
        if(this._rectanguloEti_ != null)
        {
            this._rectanguloEti_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rectanguloEti_ = node;
    }

    public PX getX()
    {
        return this._x_;
    }

    public void setX(PX node)
    {
        if(this._x_ != null)
        {
            this._x_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x_ = node;
    }

    public PY getY()
    {
        return this._y_;
    }

    public void setY(PY node)
    {
        if(this._y_ != null)
        {
            this._y_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._y_ = node;
    }

    public TWidth getWidth()
    {
        return this._width_;
    }

    public void setWidth(TWidth node)
    {
        if(this._width_ != null)
        {
            this._width_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._width_ = node;
    }

    public THeight getHeight()
    {
        return this._height_;
    }

    public void setHeight(THeight node)
    {
        if(this._height_ != null)
        {
            this._height_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._height_ = node;
    }

    public PStyle getStyle()
    {
        return this._style_;
    }

    public void setStyle(PStyle node)
    {
        if(this._style_ != null)
        {
            this._style_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._style_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rectanguloEti_)
            + toString(this._x_)
            + toString(this._y_)
            + toString(this._width_)
            + toString(this._height_)
            + toString(this._style_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rectanguloEti_ == child)
        {
            this._rectanguloEti_ = null;
            return;
        }

        if(this._x_ == child)
        {
            this._x_ = null;
            return;
        }

        if(this._y_ == child)
        {
            this._y_ = null;
            return;
        }

        if(this._width_ == child)
        {
            this._width_ = null;
            return;
        }

        if(this._height_ == child)
        {
            this._height_ = null;
            return;
        }

        if(this._style_ == child)
        {
            this._style_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rectanguloEti_ == oldChild)
        {
            setRectanguloEti((TRectanguloEti) newChild);
            return;
        }

        if(this._x_ == oldChild)
        {
            setX((PX) newChild);
            return;
        }

        if(this._y_ == oldChild)
        {
            setY((PY) newChild);
            return;
        }

        if(this._width_ == oldChild)
        {
            setWidth((TWidth) newChild);
            return;
        }

        if(this._height_ == oldChild)
        {
            setHeight((THeight) newChild);
            return;
        }

        if(this._style_ == oldChild)
        {
            setStyle((PStyle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
