/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ARx extends PRx
{
    private TRxw _rxw_;
    private TValor _valor_;

    public ARx()
    {
        // Constructor
    }

    public ARx(
        @SuppressWarnings("hiding") TRxw _rxw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setRxw(_rxw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new ARx(
            cloneNode(this._rxw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARx(this);
    }

    public TRxw getRxw()
    {
        return this._rxw_;
    }

    public void setRxw(TRxw node)
    {
        if(this._rxw_ != null)
        {
            this._rxw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rxw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rxw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rxw_ == child)
        {
            this._rxw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rxw_ == oldChild)
        {
            setRxw((TRxw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
