/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ARy extends PRy
{
    private TRyw _ryw_;
    private TValor _valor_;

    public ARy()
    {
        // Constructor
    }

    public ARy(
        @SuppressWarnings("hiding") TRyw _ryw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setRyw(_ryw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new ARy(
            cloneNode(this._ryw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARy(this);
    }

    public TRyw getRyw()
    {
        return this._ryw_;
    }

    public void setRyw(TRyw node)
    {
        if(this._ryw_ != null)
        {
            this._ryw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ryw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ryw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ryw_ == child)
        {
            this._ryw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ryw_ == oldChild)
        {
            setRyw((TRyw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
