/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStrokewidth extends PStrokewidth
{
    private TStrokewidthw _strokewidthw_;
    private TValor _valor_;

    public AStrokewidth()
    {
        // Constructor
    }

    public AStrokewidth(
        @SuppressWarnings("hiding") TStrokewidthw _strokewidthw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setStrokewidthw(_strokewidthw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AStrokewidth(
            cloneNode(this._strokewidthw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrokewidth(this);
    }

    public TStrokewidthw getStrokewidthw()
    {
        return this._strokewidthw_;
    }

    public void setStrokewidthw(TStrokewidthw node)
    {
        if(this._strokewidthw_ != null)
        {
            this._strokewidthw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strokewidthw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strokewidthw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strokewidthw_ == child)
        {
            this._strokewidthw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strokewidthw_ == oldChild)
        {
            setStrokewidthw((TStrokewidthw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
