/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AX extends PX
{
    private TXw _xw_;
    private TValor _valor_;

    public AX()
    {
        // Constructor
    }

    public AX(
        @SuppressWarnings("hiding") TXw _xw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setXw(_xw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AX(
            cloneNode(this._xw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAX(this);
    }

    public TXw getXw()
    {
        return this._xw_;
    }

    public void setXw(TXw node)
    {
        if(this._xw_ != null)
        {
            this._xw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._xw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._xw_ == child)
        {
            this._xw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._xw_ == oldChild)
        {
            setXw((TXw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
