/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AX2 extends PX2
{
    private TX2w _x2w_;
    private TValor _valor_;

    public AX2()
    {
        // Constructor
    }

    public AX2(
        @SuppressWarnings("hiding") TX2w _x2w_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setX2w(_x2w_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AX2(
            cloneNode(this._x2w_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAX2(this);
    }

    public TX2w getX2w()
    {
        return this._x2w_;
    }

    public void setX2w(TX2w node)
    {
        if(this._x2w_ != null)
        {
            this._x2w_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x2w_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._x2w_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._x2w_ == child)
        {
            this._x2w_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._x2w_ == oldChild)
        {
            setX2w((TX2w) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
