/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AY extends PY
{
    private TYw _yw_;
    private TValor _valor_;

    public AY()
    {
        // Constructor
    }

    public AY(
        @SuppressWarnings("hiding") TYw _yw_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setYw(_yw_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AY(
            cloneNode(this._yw_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAY(this);
    }

    public TYw getYw()
    {
        return this._yw_;
    }

    public void setYw(TYw node)
    {
        if(this._yw_ != null)
        {
            this._yw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._yw_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._yw_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._yw_ == child)
        {
            this._yw_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._yw_ == oldChild)
        {
            setYw((TYw) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
