/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AY1 extends PY1
{
    private TY1w _y1w_;
    private TValor _valor_;

    public AY1()
    {
        // Constructor
    }

    public AY1(
        @SuppressWarnings("hiding") TY1w _y1w_,
        @SuppressWarnings("hiding") TValor _valor_)
    {
        // Constructor
        setY1w(_y1w_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AY1(
            cloneNode(this._y1w_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAY1(this);
    }

    public TY1w getY1w()
    {
        return this._y1w_;
    }

    public void setY1w(TY1w node)
    {
        if(this._y1w_ != null)
        {
            this._y1w_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._y1w_ = node;
    }

    public TValor getValor()
    {
        return this._valor_;
    }

    public void setValor(TValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._y1w_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._y1w_ == child)
        {
            this._y1w_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._y1w_ == oldChild)
        {
            setY1w((TY1w) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((TValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
