/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TEspacio extends Token
{
    public TEspacio()
    {
        super.setText(" ");
    }

    public TEspacio(int line, int pos)
    {
        super.setText(" ");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEspacio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEspacio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEspacio text.");
    }
}
