/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 0;
    }

    @Override
    public void caseTComa(@SuppressWarnings("unused") TComa node)
    {
        this.index = 1;
    }

    @Override
    public void caseTEspacio(@SuppressWarnings("unused") TEspacio node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFinfigura(@SuppressWarnings("unused") TFinfigura node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTab(@SuppressWarnings("unused") TTab node)
    {
        this.index = 4;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 5;
    }

    @Override
    public void caseTAbrir(@SuppressWarnings("unused") TAbrir node)
    {
        this.index = 6;
    }

    @Override
    public void caseTCerrar(@SuppressWarnings("unused") TCerrar node)
    {
        this.index = 7;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 8;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 9;
    }

    @Override
    public void caseTAlert(@SuppressWarnings("unused") TAlert node)
    {
        this.index = 10;
    }

    @Override
    public void caseTDoctype(@SuppressWarnings("unused") TDoctype node)
    {
        this.index = 11;
    }

    @Override
    public void caseTValor(@SuppressWarnings("unused") TValor node)
    {
        this.index = 12;
    }

    @Override
    public void caseTAtributo(@SuppressWarnings("unused") TAtributo node)
    {
        this.index = 13;
    }

    @Override
    public void caseTBody(@SuppressWarnings("unused") TBody node)
    {
        this.index = 14;
    }

    @Override
    public void caseTFinbody(@SuppressWarnings("unused") TFinbody node)
    {
        this.index = 15;
    }

    @Override
    public void caseTSvgEti(@SuppressWarnings("unused") TSvgEti node)
    {
        this.index = 16;
    }

    @Override
    public void caseTCirculoEti(@SuppressWarnings("unused") TCirculoEti node)
    {
        this.index = 17;
    }

    @Override
    public void caseTRectanguloEti(@SuppressWarnings("unused") TRectanguloEti node)
    {
        this.index = 18;
    }

    @Override
    public void caseTLineaEti(@SuppressWarnings("unused") TLineaEti node)
    {
        this.index = 19;
    }

    @Override
    public void caseTElipseEti(@SuppressWarnings("unused") TElipseEti node)
    {
        this.index = 20;
    }

    @Override
    public void caseTPoligonoEti(@SuppressWarnings("unused") TPoligonoEti node)
    {
        this.index = 21;
    }

    @Override
    public void caseTPolilineaEti(@SuppressWarnings("unused") TPolilineaEti node)
    {
        this.index = 22;
    }

    @Override
    public void caseTComillas(@SuppressWarnings("unused") TComillas node)
    {
        this.index = 23;
    }

    @Override
    public void caseTHtml(@SuppressWarnings("unused") THtml node)
    {
        this.index = 24;
    }

    @Override
    public void caseTFinhtml(@SuppressWarnings("unused") TFinhtml node)
    {
        this.index = 25;
    }

    @Override
    public void caseTWidth(@SuppressWarnings("unused") TWidth node)
    {
        this.index = 26;
    }

    @Override
    public void caseTHeight(@SuppressWarnings("unused") THeight node)
    {
        this.index = 27;
    }

    @Override
    public void caseTCxw(@SuppressWarnings("unused") TCxw node)
    {
        this.index = 28;
    }

    @Override
    public void caseTCyw(@SuppressWarnings("unused") TCyw node)
    {
        this.index = 29;
    }

    @Override
    public void caseTRw(@SuppressWarnings("unused") TRw node)
    {
        this.index = 30;
    }

    @Override
    public void caseTFillw(@SuppressWarnings("unused") TFillw node)
    {
        this.index = 31;
    }

    @Override
    public void caseTStrokew(@SuppressWarnings("unused") TStrokew node)
    {
        this.index = 32;
    }

    @Override
    public void caseTStrokewidthw(@SuppressWarnings("unused") TStrokewidthw node)
    {
        this.index = 33;
    }

    @Override
    public void caseTStylew(@SuppressWarnings("unused") TStylew node)
    {
        this.index = 34;
    }

    @Override
    public void caseTX1w(@SuppressWarnings("unused") TX1w node)
    {
        this.index = 35;
    }

    @Override
    public void caseTX2w(@SuppressWarnings("unused") TX2w node)
    {
        this.index = 36;
    }

    @Override
    public void caseTY1w(@SuppressWarnings("unused") TY1w node)
    {
        this.index = 37;
    }

    @Override
    public void caseTY2w(@SuppressWarnings("unused") TY2w node)
    {
        this.index = 38;
    }

    @Override
    public void caseTFinsvg(@SuppressWarnings("unused") TFinsvg node)
    {
        this.index = 39;
    }

    @Override
    public void caseTXw(@SuppressWarnings("unused") TXw node)
    {
        this.index = 40;
    }

    @Override
    public void caseTYw(@SuppressWarnings("unused") TYw node)
    {
        this.index = 41;
    }

    @Override
    public void caseTRxw(@SuppressWarnings("unused") TRxw node)
    {
        this.index = 42;
    }

    @Override
    public void caseTRyw(@SuppressWarnings("unused") TRyw node)
    {
        this.index = 43;
    }

    @Override
    public void caseTPointsw(@SuppressWarnings("unused") TPointsw node)
    {
        this.index = 44;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 45;
    }
}
